// <auto-generated />
namespace PayPal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Orders_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Orders_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041201043_add_Orders_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
